(global-set-key (kbd "M-s") 'save-buffer)
(global-set-key (kbd "M-c") 'kill-ring-save)
(global-set-key (kbd "M-v") 'yank)
(global-set-key (kbd "M-z") 'undo)

(with-eval-after-load 'evil
  (define-key evil-normal-state-map (kbd "<return>")
    (lambda ()
      (interactive)
      (if buffer-read-only
          (call-interactively (or (local-key-binding (kbd "<return>"))
                                  (local-key-binding (kbd "RET"))
                                  #'push-button))
        (evil-open-below 1))))
  (define-key evil-normal-state-map (kbd "s") 'lsp-find-references)
  (define-key evil-normal-state-map (kbd "d") 'lsp-find-definition)
  (define-key evil-normal-state-map (kbd "b") 'evil-jump-backward)
  (define-key evil-normal-state-map (kbd "f f")
    (lambda ()
      (interactive)
      (let* ((root (projectile-project-root))
             (files (projectile-project-files root))
             (alist (mapcar
                     (lambda (f)
                       (cons (file-name-nondirectory f) f))
                     files))
             (completion-extra-properties
              (list :annotation-function
                    (lambda (c) (concat "  " (file-name-directory (cdr (assoc c alist)))))))
             (completion-ignore-case t)
             (chosen (completing-read "Find file: " alist nil t)))
        (find-file (expand-file-name (cdr (assoc chosen alist)) root)))))
  (define-key evil-normal-state-map (kbd "f s")
    (lambda ()
      (interactive)
      (consult-ripgrep (projectile-project-root) (thing-at-point 'symbol t))))
  (define-key evil-normal-state-map (kbd "f g")
    (lambda ()
      (interactive)
      (consult-ripgrep (projectile-project-root))))
  (define-key evil-normal-state-map (kbd "c") 'delete-window)
  (define-key evil-normal-state-map (kbd "SPC /") 'split-window-horizontally)
  (define-key evil-normal-state-map (kbd "x") 'kill-whole-line))

(global-set-key (kbd "M-r") (lambda ()
                               (interactive)
                               (load-file "~/.emacs.d/init.el")
                               (message "Config reloaded.")))
