(global-set-key (kbd "M-s") 'save-buffer)
(global-set-key (kbd "M-c") 'kill-ring-save)
(global-set-key (kbd "M-v")
  (lambda ()
    (interactive)
    (let ((start (point)))
      (yank)
      (indent-region start (point)))))
(global-set-key (kbd "M-z") 'undo)

(defun my-hungry-backspace ()
  (interactive)
  (if (use-region-p)
      (delete-region (region-beginning) (region-end))
    (if (save-excursion
          (skip-chars-backward " \t")
          (bolp))
        (progn
          (delete-region (line-beginning-position) (point))
          (delete-char -1))
      (delete-char -1))))

(with-eval-after-load 'evil
  (define-key evil-insert-state-map (kbd "DEL") 'my-hungry-backspace)
  (define-key evil-normal-state-map (kbd "<return>")
    (lambda ()
      (interactive)
      (if buffer-read-only
          (call-interactively (or (local-key-binding (kbd "<return>"))
                                  (local-key-binding (kbd "RET"))
                                  #'push-button))
        (evil-open-below 1))))
  (define-key evil-normal-state-map (kbd "s") 'lsp-find-references)
  (define-key evil-normal-state-map (kbd "d") 'lsp-find-definition)
  (define-key evil-normal-state-map (kbd "b") 'evil-jump-backward)
  (define-key evil-normal-state-map (kbd "f f")
    (lambda ()
      (interactive)
      (let* ((root (projectile-project-root))
             (files (projectile-project-files root))
             (sorted (sort files
                           (lambda (a b)
                             (and (string-prefix-p "src/" a)
                                  (not (string-prefix-p "src/" b))))))
             (name-to-path (make-hash-table :test 'equal))
             (src-set (make-hash-table :test 'equal))
             (alist (mapcar
                     (lambda (f)
                       (let ((name (file-name-nondirectory f)))
                         (puthash name f name-to-path)
                         (when (string-prefix-p "src/" f)
                           (puthash name t src-set))
                         (cons name f)))
                     sorted))
             (completion-extra-properties
              (list :annotation-function
                    (lambda (c) (concat "  " (file-name-directory (gethash c name-to-path))))))
             (completion-ignore-case t)
             (hist-set (make-hash-table :test 'equal))
             (_ (when (bound-and-true-p minibuffer-history-variable)
                  (dolist (h (symbol-value minibuffer-history-variable))
                    (puthash h t hist-set))))
             (hist-list (when (bound-and-true-p minibuffer-history-variable)
                          (symbol-value minibuffer-history-variable)))
             (sort-fn (lambda (candidates)
                        (let ((cand-set (make-hash-table :test 'equal))
                              hist-items src-items rest-items)
                          (dolist (c candidates)
                            (puthash c t cand-set))
                          (dolist (h hist-list)
                            (when (gethash h cand-set)
                              (push h hist-items)
                              (remhash h cand-set)))
                          (setq hist-items (nreverse hist-items))
                          (dolist (c candidates)
                            (when (gethash c cand-set)
                              (if (gethash c src-set)
                                  (push c src-items)
                                (push c rest-items))))
                          (append hist-items (nreverse src-items) (nreverse rest-items)))))
             (chosen (completing-read "Find file: "
                       (lambda (str pred action)
                         (if (eq action 'metadata)
                             `(metadata (display-sort-function . ,sort-fn)
                                        (cycle-sort-function . ,sort-fn))
                           (complete-with-action action alist str pred)))
                       nil t)))
        (find-file (expand-file-name (gethash chosen name-to-path) root)))))
  (define-key evil-normal-state-map (kbd "f s")
    (lambda ()
      (interactive)
      (consult-ripgrep (projectile-project-root) (thing-at-point 'symbol t))))
  (define-key evil-normal-state-map (kbd "f g")
    (lambda ()
      (interactive)
      (consult-ripgrep (projectile-project-root))))
  (define-key evil-normal-state-map (kbd "c") 'delete-window)
  (define-key evil-normal-state-map (kbd "SPC /") 'split-window-horizontally)
  (define-key evil-normal-state-map (kbd "x") 'kill-whole-line))

(global-set-key (kbd "M-r") (lambda ()
                               (interactive)
                               (load-file "~/.emacs.d/init.el")
                               (message "Config reloaded.")))
